# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  push:
      branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      # Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: shrawak
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: git status

        # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Generate Contribution Snake' 
      
#       - name: Generate Snake
#         uses: Platane/snk@master
#         id: snake-gif
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           gif_out_path: ./assets/github-contribution-grid-snake.gif
#           svg_out_path: ./assets/github-contribution-grid-snake.svg
            

#       - name: Push to GitHub
#         uses: EndBug/add-and-commit@v7.2.1
#         with:
#           branch: main
#           message: 'Generate Contribution Snake'      
